services:
  rabbitmq:
    image: rabbitmq:4.0-management
    hostname: obsidian-sync
    container_name: obsidian-sync
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
  container-1:
    build: .
    container_name: container-1
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - CLIENT_ID=t-client-1
      - RABBITMQ_ADDRESS=amqp://kappa:chungus@rabbitmq:5672/
      - RABBITMQ_EXCHANGE_NAME=neco
      - RABBITMQ_QUEUE_NAME=t-queue-1
      - RABBITMQ_ROUTING_KEY=kappa.penis
      - SYNC_DIRECTORY=/app
  container-2:
    build: .
    container_name: container-2
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - CLIENT_ID=t-client-2
      - RABBITMQ_ADDRESS=amqp://kappa:chungus@rabbitmq:5672/
      - RABBITMQ_EXCHANGE_NAME=neco
      - RABBITMQ_QUEUE_NAME=t-queue-2
      - RABBITMQ_ROUTING_KEY=kappa.penis
      - SYNC_DIRECTORY=/app
volumes:
  rabbitmq-data: