services:
  rabbitmq:
    image: rabbitmq:4.0-management
    hostname: obsidian-sync
    container_name: obsidian-sync
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
  container-1:
    build:
      context: .
      dockerfile: integration_test/client.Dockerfile
    container_name: container-1
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - CLIENT_ID=t-client-1
      - RABBITMQ_ADDRESS=amqp://kappa:chungus@rabbitmq:5672/
      - RABBITMQ_EXCHANGE_NAME=neco
      - RABBITMQ_QUEUE_NAME=t-queue-1
      - RABBITMQ_ROUTING_KEY=kappa.penis
      - SYNC_DIRECTORY=/app/sync
      - SYNC_SERVER_URL=http://file-server:8080
  file-server:
    build:
      context: .
      dockerfile: integration_test/server.Dockerfile
    container_name: file-server
    ports:
      - "8080:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - CLIENT_ID=server-pub
      - SYNC_DIRECTORY=/app/storage
      - RABBITMQ_ADDRESS=amqp://kappa:chungus@rabbitmq:5672/
      - RABBITMQ_EXCHANGE_NAME=neco
      - RABBITMQ_ROUTING_KEY=kappa.penis
volumes:
  rabbitmq-data: