name: Necoconeco CI/CD

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.8'

      - name: Tidy Go modules
        run: go mod tidy

      - name: Build  'client' application
        run: go build -v -tags client -o necoconeco-client .

      - name: Build 'server' application
        run: go build -v -tags server -o necoconeco-server .

      - name: Run Go tests
        run: go test -v ./...

  push-docker-image:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: build-and-test
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker image to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./integration_test/server.Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/necoconeco-server:latest